//! Runtime enable/disable of a forced high-refresh "virtual" display via xrandr.
//!
//! The virtual output (default `DP-2`) is a forced-connected connector whose
//! CustomEDID advertises high-refresh modes. The one-time Xorg config + EDID are
//! auto-installed via `pkexec` (a graphical auth prompt) the first time the user
//! enables the virtual screen — see [`provision`]. After a single X restart the
//! connector stays forced across reboots and enable/disable is pure xrandr.

use std::io::Write;
use std::process::Command;

/// 128-byte EDID advertising 1920x1080 @ 240/144/120/60 Hz (see
/// `scripts/virtual-display/gen_edid.py`), embedded so the agent can install it
/// without shipping the file separately.
const DP2_EDID: &[u8] = include_bytes!("../../scripts/virtual-display/dp2-1080p-highrefresh.bin");
const XORG_CONF_PATH: &str = "/etc/X11/xorg.conf.d/20-lunaris-virtual-dp2.conf";
const EDID_INSTALL_PATH: &str = "/etc/X11/lunaris-dp2-edid.bin";

/// Enable the virtual display: set `output` to `width`x`height` at ~`refresh_hz`,
/// positioned to the right of the primary, leaving the primary output unchanged.
pub fn enable(output: &str, width: u32, height: u32, refresh_hz: u32) -> Result<(), String> {
    let text = query().ok_or_else(|| "xrandr --query failed".to_string())?;

    if !output_connected(&text, output) {
        // The forced connector isn't active yet. Either the one-time Xorg config
        // hasn't been installed, or it's installed but X hasn't been restarted.
        if config_installed() {
            return Err(format!(
                "Virtual display config is installed but not active yet. Log out and \
                 back in (or restart X) once to activate '{}', then Enable again.",
                output
            ));
        }
        return match provision(&text, output) {
            Ok(()) => Err(format!(
                "Virtual display support installed. Log out and back in (or restart X) \
                 once to activate '{}', then press Enable again.",
                output
            )),
            Err(e) => Err(format!(
                "Automatic setup failed: {}. You can run \
                 scripts/virtual-display/apply.sh manually instead.",
                e
            )),
        };
    }

    let rate = closest_advertised_rate(&text, output, refresh_hz).ok_or_else(|| {
        format!(
            "Output '{}' advertises no mode near {}Hz. Regenerate the EDID \
             (scripts/virtual-display/gen_edid.py) to include it.",
            output, refresh_hz
        )
    })?;

    let primary = primary_output(&text);
    let mode = format!("{}x{}", width, height);
    let mut args: Vec<String> = Vec::new();
    if let Some(p) = &primary {
        args.extend(["--output".into(), p.clone(), "--primary".into()]);
    }
    args.extend([
        "--output".into(),
        output.to_string(),
        "--mode".into(),
        mode,
        "--rate".into(),
        format!("{:.2}", rate),
    ]);
    if let Some(p) = &primary {
        args.extend(["--right-of".into(), p.clone()]);
    }
    run_xrandr(&args)
}

/// Turn the virtual display output off.
pub fn disable(output: &str) -> Result<(), String> {
    run_xrandr(&[
        "--output".to_string(),
        output.to_string(),
        "--off".to_string(),
    ])
}

/// Whether the forced virtual-display Xorg config is already installed.
fn config_installed() -> bool {
    std::path::Path::new(XORG_CONF_PATH).exists()
}

/// Install the forced-connector Xorg config + EDID for `output` via `pkexec`
/// (a graphical polkit auth prompt). Does NOT restart X — the caller tells the
/// user to log out/in once. The `ConnectedMonitor` list keeps every currently
/// connected output plus `output`, so real monitors are never disabled.
fn provision(text: &str, output: &str) -> Result<(), String> {
    if which("pkexec").is_none() {
        return Err(
            "pkexec not found; cannot auto-install (install polkit, or run \
             scripts/virtual-display/apply.sh)"
                .into(),
        );
    }

    let mut monitors = connected_outputs(text);
    if !monitors.iter().any(|m| m == output) {
        monitors.push(output.to_string());
    }
    let connected_list = monitors.join(", ");

    let conf = format!(
"# Auto-generated by the Lunaris agent — forced high-refresh virtual display.
Section \"Device\"
    Identifier  \"LunarisNvidia\"
    Driver      \"nvidia\"
    Option      \"ConnectedMonitor\" \"{list}\"
    Option      \"CustomEDID\" \"{out}:{edid}\"
    Option      \"ModeValidation\" \"{out}: NoMaxPClkCheck, NoEdidMaxPClkCheck\"
    Option      \"AllowEmptyInitialConfiguration\" \"true\"
EndSection
",
        list = connected_list,
        out = output,
        edid = EDID_INSTALL_PATH
    );

    // Stage agent-writable files, then install them as root via pkexec.
    let dir = std::env::temp_dir();
    let edid_tmp = dir.join("lunaris-dp2-edid.bin");
    let conf_tmp = dir.join("lunaris-virtual-dp2.conf");
    let script_tmp = dir.join("lunaris-vd-install.sh");

    write_file(&edid_tmp, DP2_EDID)?;
    write_file(&conf_tmp, conf.as_bytes())?;
    let script = format!(
        "#!/bin/bash\nset -e\ninstall -m 0644 '{}' '{}'\ninstall -m 0644 '{}' '{}'\n",
        edid_tmp.display(),
        EDID_INSTALL_PATH,
        conf_tmp.display(),
        XORG_CONF_PATH,
    );
    write_file(&script_tmp, script.as_bytes())?;

    let status = Command::new("pkexec")
        .arg("/bin/bash")
        .arg(&script_tmp)
        .status()
        .map_err(|e| format!("failed to run pkexec: {}", e))?;

    let _ = std::fs::remove_file(&edid_tmp);
    let _ = std::fs::remove_file(&conf_tmp);
    let _ = std::fs::remove_file(&script_tmp);

    if status.success() {
        log::info!(
            "Installed virtual-display config for '{}' (ConnectedMonitor: {})",
            output,
            connected_list
        );
        Ok(())
    } else {
        Err("authentication was cancelled or the install command failed".into())
    }
}

fn write_file(path: &std::path::Path, bytes: &[u8]) -> Result<(), String> {
    let mut f = std::fs::File::create(path)
        .map_err(|e| format!("cannot write {}: {}", path.display(), e))?;
    f.write_all(bytes)
        .map_err(|e| format!("cannot write {}: {}", path.display(), e))
}

fn which(cmd: &str) -> Option<std::path::PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths).find_map(|dir| {
            let p = dir.join(cmd);
            if p.is_file() {
                Some(p)
            } else {
                None
            }
        })
    })
}

/// Names of all currently-connected outputs parsed from `xrandr --query` text.
fn connected_outputs(text: &str) -> Vec<String> {
    text.lines()
        .filter(|l| !l.starts_with(char::is_whitespace) && l.contains(" connected"))
        .filter_map(|l| l.split_whitespace().next().map(|s| s.to_string()))
        .collect()
}

/// Override each display's `refresh_rate` with the real active rate reported by
/// xrandr. NvFBC's `list_displays` hardcodes 60.0, so without this a virtual
/// display running at 240Hz would still be labelled 60Hz in the client UI.
/// Displays are matched by connector name.
pub fn enrich_refresh_rates(displays: &mut [common::DisplayInfoMsg]) {
    let text = match query() {
        Some(t) => t,
        None => return,
    };
    for d in displays.iter_mut() {
        if let Some(rate) = active_rate(&text, &d.name) {
            d.refresh_rate = rate;
        }
    }
}

// ---- xrandr helpers ----

fn run_xrandr(args: &[String]) -> Result<(), String> {
    let out = Command::new("xrandr")
        .args(args)
        .output()
        .map_err(|e| format!("failed to run xrandr: {}", e))?;
    if out.status.success() {
        Ok(())
    } else {
        Err(format!(
            "xrandr failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        ))
    }
}

fn query() -> Option<String> {
    let out = Command::new("xrandr").arg("--query").output().ok()?;
    if out.status.success() {
        Some(String::from_utf8_lossy(&out.stdout).into_owned())
    } else {
        None
    }
}

fn output_connected(text: &str, output: &str) -> bool {
    text.lines().any(|l| {
        !l.starts_with(char::is_whitespace)
            && l.split_whitespace().next() == Some(output)
            && l.contains(" connected")
    })
}

fn primary_output(text: &str) -> Option<String> {
    text.lines()
        .find(|l| l.contains(" connected") && l.contains(" primary"))
        .and_then(|l| l.split_whitespace().next().map(|s| s.to_string()))
}

/// Return the advertised refresh rate for `output` closest to `target_hz`,
/// within a 2 Hz tolerance.
fn closest_advertised_rate(text: &str, output: &str, target_hz: u32) -> Option<f64> {
    let target = target_hz as f64;
    output_rates(text, output)
        .into_iter()
        .filter(|r| (r - target).abs() <= 2.0)
        .min_by(|a, b| {
            (a - target)
                .abs()
                .partial_cmp(&(b - target).abs())
                .unwrap_or(std::cmp::Ordering::Equal)
        })
}

/// The currently-active refresh rate (marked with `*`) for `output`.
fn active_rate(text: &str, output: &str) -> Option<f64> {
    let mut in_block = false;
    for line in text.lines() {
        let is_header = !line.is_empty() && !line.starts_with(char::is_whitespace);
        if is_header {
            in_block = line.split_whitespace().next() == Some(output);
            continue;
        }
        if !in_block {
            continue;
        }
        for tok in line.split_whitespace() {
            if tok.contains('*') {
                if let Ok(r) = tok.trim_end_matches(|c| c == '*' || c == '+').parse::<f64>() {
                    return Some(r);
                }
            }
        }
    }
    None
}

/// All advertised refresh rates for `output`.
fn output_rates(text: &str, output: &str) -> Vec<f64> {
    let mut rates = Vec::new();
    let mut in_block = false;
    for line in text.lines() {
        let is_header = !line.is_empty() && !line.starts_with(char::is_whitespace);
        if is_header {
            in_block = line.split_whitespace().next() == Some(output);
            continue;
        }
        if !in_block {
            continue;
        }
        for tok in line.split_whitespace() {
            let cleaned = tok.trim_end_matches(|c| c == '*' || c == '+');
            if let Ok(r) = cleaned.parse::<f64>() {
                rates.push(r);
            }
        }
    }
    rates
}
